# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RtaCocos-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RtaCocos-desktop

end

target 'RtaCocos-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RtaCocos-mobile
  pod 'KwizzadRTA', '0.2.5'
end
